POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "title": "hello",
  "userId": "321",
  "type": "TEXT",
  "status": "DRAFT",
  "announce": "announce",
  "postText": "text",
  "id": "87c8fa30-f703-42aa-9ebd-bba2ed0870cd"
}

###
GET http://localhost:3000/api/posts HTTP/1.1
